version: '3.8'

services:
    mongodb:
        build:
            context: .
            dockerfile: ./docker-config/mongodb/Dockerfile
        ports:
            - 27017:27017
    app:
        build:
            context: .
            dockerfile: ./docker-config/app/Dockerfile
        ports:
            - 4000:4000
        environment: 
            MONGO_HOST: mongodb
            SERVER_PORT: 4000
        volumes:
            - ./app:/src/
        links:
            - mongodb
        depends_on: 
            - mongodb